name: Guardrails
on:
  push:
    branches: ["**"]
  pull_request:

jobs:
  anti-pattern-check:
    name: Anti-pattern and OpenAPI validation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "18"
      - name: Install dependencies (minimal)
        run: |
          npm ci --ignore-scripts
      - name: Verify production flags remain disabled
        run: |
          npm run ci:verify-prod-flags
      - name: Check prohibited imports and directories
        run: |
          if grep -RIE --line-number "from ['\"]/.*\/(auth|college|idcard|campus|student)" src/ 2>/dev/null; then
            echo "❌ ERROR: Auth/college imports detected. This violates ADR-001." && exit 1; fi
          if grep -RIE --line-number "^(model|interface) (College|Campus|Student|IdCard)" prisma/schema.prisma 2>/dev/null; then
            echo "❌ ERROR: College-domain schema detected. This violates ADR-001." && exit 1; fi
          if [ -d client ] || [ -d frontend ] || [ -d public ] || [ -d views ]; then
            echo "❌ ERROR: Frontend directories detected. This violates ADR-001." && exit 1; fi
      - name: Validate OpenAPI (Redocly)
        run: |
          npx --yes @redocly/cli@latest lint docs/contracts/openapi.yaml

  build-and-test:
    name: Build, Lint, Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "18"
      - name: Install dependencies
        run: npm ci
      - name: Typecheck & Lint
        run: npm run lint
      - name: Build
        run: npm run build
      - name: Unit tests
        run: npm test -- --reporters=default --reporters=jest-junit
      - name: Upload JUnit report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: junit-results
          path: junit.xml
          if-no-files-found: ignore
